### ISSUE TITLE
ideal.py coupler

### ISSUE THREAD

**Issue by 11of12** [BYUCamachoLab/simphony#111]
Line 47 in ideal.py should not use jnp.conj() since a positive pi/2 there should be a positive pi/2 phase shift in both coupling directions. I suggest removing the jn.conj() entirely and leaving kappa be. I have tested this and we get much more sensible s-params after circuit simulations after implementing this change.

As the coupler is implemented currently, the thru port of the ring resonator is obviously wrong (it looks like a drop port and there should not be gain):
![bad_kappa](https://github.com/user-attachments/assets/0ef1ad39-14e1-4e04-b72c-90cf84300b7e)

With my correction, the ring resonator functions as expected:
![correct_kappa](https://github.com/user-attachments/assets/04f9ee69-40e5-4907-93b2-470eccdfaaf7)

**Comment by cjcarver** [comment]
Thanks for pointing this out. It is now fixed in the above commit.
