### ISSUE TITLE
Get s-parameters by wavelength

### ISSUE THREAD

**Issue by sequoiap** [BYUCamachoLab/simphony#28]
It would be nice to get the wavelength results from a simulation, instead of just frequency. Perhaps we can convert from frequency back to wavelength and reinterpolate the result to get evenly spaced wavelength points?

**Comment by AustP** [comment]
The `SweepSimulator` component now returns the simulation data in the same units that it was instantiated with.

For example: when `SweepSimulator(1500e-9, 1600e-9)` is simulated, it will return wavelengths.
