### ISSUE TITLE
Add a few examples with figures to Readme

### ISSUE THREAD

**Issue by smartalecH** [BYUCamachoLab/simphony#35]
It would be good to add a few (or even just one) example with figures to the Readme. Since this is the landing page, it's important to sell what the package does without requiring someone to scour the docs.

As always, a figure is always more valuable than just text. So tell the story with pictures.

**Comment by sequoiap** [comment]
@smartalecH Is this what you were envisioning, or something a little more detailed?

https://github.com/BYUCamachoLab/simphony/tree/readme-ex

**Comment by smartalecH** [comment]
Looks great. I would add a figure of the circuit too (i.e. a layout or even simple schematic).
