### ISSUE TITLE
Refractive index in Mach Zender Interface

### ISSUE THREAD

**Issue by ariwanski** [BYUCamachoLab/simphony#57]
Hi there, 

I am attempting to use the Mach Zender code for a school project. I would like to see the property of using an MZI with different path lengths to perform scalar multiplication. I am currently using the Laser Simulation and doing a power sweep. I then am plotting the input power vs the output power. We see a constant slope value when doing this; however, it is not the slope we would expect. 

We know that cos(phi) is the scalar factor we would multiply by. We know all values in this equation aside from n. Would n be the refractive index of silicon (~3.88163)? We just do not have insight into your backend representation of the mach zender model.
![image](https://user-images.githubusercontent.com/36748933/146470916-131983b8-6917-4920-80fe-8da397819481.png)

By the way, this is the article we are referencing. https://medium.com/lightmatter/optical-components-for-matrix-processing-73687cdd7aa6 
We are trying to replicate the scalar multiplication using your simulator. 

Any help you have is appreciated! If you have a second for a ten minute call that would also be beyond helpful. So far we've loved using your software as it provides an accessible interface to previously unattainable silicon photonic simulation.

**Comment by AustP** [comment]
Do you mind posting your source code here so I can take a look at it?

Also, you can email me at austp17@gmail.com and we can try to find a time to have a web call.

**Comment by t-d-w** [comment]
Hello, I am also working on this project. Attached is the source code (it wouldnt let me attach .py, so I converted it to .txt). We adapted the mach zender example code from the documentation and used the laser simulation from a different example so we could do a powersweep. We are really just looking to verify the correctness of the scalar multiplication which is why we were asking about index of refraction. I will send you a follow up email.

Thanks! We appreciate the help.

[mz_test.txt](https://github.com/BYUCamachoLab/simphony/files/7738089/mz_test.txt)

**Comment by AustP** [comment]
```(python)
import matplotlib.pyplot as plt
import numpy as np
from simphony import Model
from simphony.simulation import Detector, Laser, Simulation


class IdealGratingCoupler(Model):
    pins = ("in", "out")

    def s_parameters(self, freqs: "np.array") -> "np.ndarray":
        # pin layout: [in, out]
        smatrix = np.array(
            [
                [0, 1],
                [1, 0],
            ]
        )

        # the s-matrix is not frequency dependent,
        # so just return it for each frequency
        return np.repeat(smatrix, len(freqs)).reshape((len(freqs), 2, 2))


class IdealYBranch(Model):
    pins = ("base", "arm1", "arm2")

    def s_parameters(self, freqs: "np.array") -> "np.ndarray":
        # pin layout: [base, arm1, arm2]
        smatrix = np.array(
            [
                [0, 1 / np.sqrt(2), 1 / np.sqrt(2)],
                [1 / np.sqrt(2), 0, 0],
                [1 / np.sqrt(2), 0, 0],
            ]
        )

        # the s-matrix is not frequency dependent,
        # so just return it for each frequency
        return np.repeat(smatrix, len(freqs)).reshape((len(freqs), 3, 3))


class IdealWaveguide(Model):
    pins = ("in", "out")

    def __init__(self, phase=0, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.phase = phase

    def s_parameters(self, freqs: "np.array") -> "np.ndarray":
        # pin layout: [in, out]
        smatrix = np.array(
            [
                [0, np.exp(1j * self.phase)],
                [np.exp(1j * self.phase), 0],
            ]
        )

        # the s-matrix is not frequency dependent,
        # so just return it for each frequency
        return np.repeat(smatrix, len(freqs)).reshape((len(freqs), 2, 2))


# instantiate components for MZI
gc_input = IdealGratingCoupler()
y_splitter = IdealYBranch()
wg1 = IdealWaveguide()
wg2 = IdealWaveguide()
y_recombiner = IdealYBranch()
gc_output = IdealGratingCoupler()

# connect components for MZI
y_splitter.multiconnect(gc_input, wg1, wg2)
y_recombiner.multiconnect(gc_output, wg2, wg1)

phases = []
output = []
for i in range(1000):
    # calculate the new phase
    phase = i / 1000 * 2 * np.pi
    phases.append(phase)

    # replace wg2 with a new waveguide with slightly more phase difference
    wg2.disconnect()
    wg2 = IdealWaveguide(phase=phase)
    wg2.multiconnect(y_splitter, y_recombiner)

    # run the simulation with the new waveguide
    with Simulation() as sim:
        l = Laser(power=1e-3).connect(gc_input)
        Detector().connect(gc_output)

        data = sim.sample()
        output.append(data[0][0])


# plot the results
plt.plot(phases, np.array(output) * 1e6)
plt.xlabel("Field Phase Difference [rad]")
plt.ylabel("Voltage [uV]")
plt.show()
```

Here is an example script using ideal components for the grating coupler, y-branch, and waveguides. Notice that I implemented the waveguides based on how much they shift the phase. You'll have to change that if you want to do it based on length.
