### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by sequoiap** [BYUCamachoLab/simphony#76]
* Debug and fix where the CI is failing (linter errors, broken tests)
* Update dependencies (security warning)

**Comment by SkandanC** [comment]
I just want to add that some of the tests under `test_simulation.py` were failing, and I fixed those as part of my latest PR.

**Comment by SkandanC** [comment]
@sequoiap do we close this now? CI/CD is fixed in my latest PR

**Comment by sequoiap** [comment]
Closed by #79
