### ISSUE TITLE
Jax error when assigning arrays

### ISSUE THREAD

**Issue by Andeloth** [BYUCamachoLab/simphony#88]
https://github.com/BYUCamachoLab/simphony/blob/5159848376a25114ecd4d2f0d9aa4c86a96bf2e1/simphony/simulation/classical.py#L75C15-L75C15

These lines throw errors when jax is enabled since jax arrays can't be assigned new values.

**Comment by sequoiap** [comment]
Fixed in 45980e46a9fa8bc1f47fe39bdad017645314367e
