### ISSUE TITLE
Wrong dependency text for skrf

### ISSUE THREAD

**Issue by Andeloth** [BYUCamachoLab/simphony#91]
https://github.com/BYUCamachoLab/simphony/blob/ada17c5c8feb50ef8080e0f89268dbe8458e3339/pyproject.toml#L52C16-L52C16

skrf's pypi designation is "scikit-rf", not "skrf"

**Comment by sequoiap** [comment]
Fixed in 1a7903a35d82268d41ce1a2b477af84eb76a24b6
